import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import {
  embedChunks,
  embeddingColumns,
  embeddingMetadata,
} from "@/lib/knowledge/embeddings";
import type { IncidentKnowledgeType } from "@/lib/types/database";

/**
 * Index a validated incident into incident_knowledge_chunks (spec §33) so it
 * becomes a searchable precedent. Only called AFTER human validation — an
 * unvalidated incident must never enter the confirmed-knowledge space (spec
 * §2.3, §11).
 *
 * Chunks are stored first (keyword-searchable immediately); embeddings are then
 * generated via the local Ollama service. If embedding is unavailable, the
 * chunks remain with null vectors and are regenerated by
 * `npm run embeddings:reindex` — closure never fails because Ollama is down, and
 * unembedded chunks are never treated as embedded.
 */
export interface KnowledgePiece {
  type: IncidentKnowledgeType;
  content: string;
}

export async function indexIncidentKnowledge(
  supabase: SupabaseClient,
  incidentId: string,
  pieces: KnowledgePiece[],
): Promise<{ indexed: number; embedded: boolean }> {
  const nonEmpty = pieces.filter((p) => p.content.trim().length > 0);
  if (nonEmpty.length === 0) return { indexed: 0, embedded: false };

  // Re-indexing an incident replaces its prior knowledge chunks.
  await supabase.from("incident_knowledge_chunks").delete().eq("incident_id", incidentId);

  // 1. Store chunks first (embedding null).
  const baseRows = nonEmpty.map((piece) => ({
    incident_id: incidentId,
    knowledge_type: piece.type,
    content: piece.content,
  }));
  const { data: inserted, error: insertError } = await supabase
    .from("incident_knowledge_chunks")
    .insert(baseRows)
    .select("id")
    .returns<{ id: string }[]>();
  if (insertError || !inserted) {
    throw new Error(`Failed to index incident knowledge: ${insertError?.message}`);
  }

  // 2. Embed best-effort; on failure keep keyword-only (retriable via reindex).
  try {
    const meta = embeddingMetadata();
    const vectors = await embedChunks(nonEmpty.map((p) => p.content));
    for (let i = 0; i < inserted.length; i++) {
      const { error } = await supabase
        .from("incident_knowledge_chunks")
        .update(embeddingColumns(vectors[i]!, meta))
        .eq("id", inserted[i]!.id);
      if (error) throw new Error(error.message);
    }
    return { indexed: baseRows.length, embedded: true };
  } catch (err) {
    console.error(
      "[incident-indexing] embedding failed, chunks stored keyword-only (retriable):",
      (err as Error).message,
    );
    return { indexed: baseRows.length, embedded: false };
  }
}
